INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta1', 'https://i.postimg.cc/9MkGM2qN/Pregunta1-Basico.png', '15', 'Basico');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta2', 'https://i.postimg.cc/T1Wn5sV2/Pregunta2-Basico.png', '30', 'Basico');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta3', 'https://i.postimg.cc/RZTp03Cs/Pregunta3-Basico.png', '168', 'Basico');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta4', 'https://i.postimg.cc/QdDnsgDK/Pregunta4-Basico.png', '10', 'Basico');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta5', 'https://i.postimg.cc/T2Z4NMH9/Pregunta5-Basico.png', '16', 'Basico');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta6', 'https://i.postimg.cc/sfBLJDKx/Pregunta6-Basico.png', 'impar', 'Basico');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta7', 'https://i.postimg.cc/dtrSzHbK/Pregunta7-Basico.png', '5', 'Basico');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta8', 'https://i.postimg.cc/8CPKf1j1/Pregunta8-Basico.png', '120', 'Basico');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta9', 'https://i.postimg.cc/VNG7j3CX/Pregunta9-Basico.png', '2', 'Basico');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta10', 'https://i.postimg.cc/xCX6gtvh/Pregunta10-Basico.png', '12', 'Basico');

INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta1', 'https://i.postimg.cc/fbmZHLkZ/Pregunta1-Intermedio.png', '4', 'Intermedio');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta2', 'https://i.postimg.cc/6pDtLRWY/Pregunta2-Intermedio.png', '1', 'Intermedio');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta3', 'https://i.postimg.cc/HW2WDVzk/Pregunta3-Intermedio.png', 'manzana', 'Intermedio');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta4', 'https://i.postimg.cc/L8qm1vpJ/Pregunta4-Intermedio.png', '15', 'Intermedio');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta5', 'https://i.postimg.cc/CLxhFSrH/Pregunta5-Intermedio.png', 'no', 'Intermedio');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta6', 'https://i.postimg.cc/bJRPhBQB/Pregunta6-Intermedio.png', 'si', 'Intermedio');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta7', 'https://i.postimg.cc/MTwwgSjB/Pregunta7-Intermedio.png', '4', 'Intermedio');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta8', 'https://i.postimg.cc/NFfcfkDf/Pregunta8-Intermedio.png', '3', 'Intermedio');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta9', 'https://i.postimg.cc/3rnhfzry/Pregunta9-Intermedio.png', '5040', 'Intermedio');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta10', 'https://i.postimg.cc/sx6RBGHP/Pregunta10-Intermedio.png', 'vida', 'Intermedio');

INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta1', 'https://i.postimg.cc/pLB3yF9m/Pregunta1-Avanzado.png', '2', 'Avanzado');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta2', 'https://i.postimg.cc/GhGWwNdJ/Pregunta2-Avanzado.png', '64', 'Avanzado');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta3', 'https://i.postimg.cc/NjtWg40h/Pregunta3-Avanzado.png', 'Juan 25', 'Avanzado');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta4', 'https://i.postimg.cc/cC8c3VXD/Pregunta4-Avanzado.png', '23', 'Avanzado');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta5', 'https://i.postimg.cc/66DkPwJp/Pregunta5-Avanzado.png', '55', 'Avanzado');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta6', 'https://i.postimg.cc/7b8nnmRq/Pregunta6-Avanzado.png', '6', 'Avanzado');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta7', 'https://i.postimg.cc/2jbpTytt/Pregunta7-Avanzado.png', '19', 'Avanzado');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta8', 'https://i.postimg.cc/bvNWnwb3/Pregunta8-Avanzado.png', '10', 'Avanzado');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta9', 'https://i.postimg.cc/DzjDP3PF/Pregunta9-Avanzado.png', 'no', 'Avanzado');
INSERT INTO repositorios(titulo,url,respuesta,nivel) VALUES ('Pregunta10', 'https://i.postimg.cc/TwKskNtb/Pregunta10-Avanzado.png', '32', 'Avanzado');